apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderpayment
spec:
  selector:
    matchLabels:
      app: orderpayment

  template:
    metadata:
      labels:
        app: orderpayment
    spec:
      containers:
        - name: orderpayment
          image: wesleywillians/intensivo-order:v2
          command: ["./order"]
          args: ["-opt", "payment"]
          ports:
            - containerPort: 6572
          env:
            - name: PRODUCT_URL
              value: "http://product-service:8081"
            - name: RABBITMQ_ERLANG_COOKIE
              value: "SWQOKODSQALRPCLNMEQG"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: RABBITMQ_DEFAULT_HOST
              value: "rabbitmq-service"
            - name: REDIS_HOST
              value: "redis-service:6379"

---

apiVersion: v1
kind: Service
metadata:
  name: orderpayment-service
  labels:
    app: orderpayment-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6572
  selector:
    app: orderpayment